### DISCUSSION TITLE
ArchDoc Specification - Add the concept of an External System

### DISCUSSION THREAD

**Discussion by mtfuller** [ArchDoc/ArchDoc.github.io#3] [Ideas]
The C4 architecture framework has notation to describe external software systems. I think it would be helpful to identify those as their own category, like so:

```yaml
externalSystems:
  vendorSystem:
    description: The external system
    tags:
      - vendor
      - public
     documentation: This external system is run by our vendor.
```

This project is still young, so I'm jotting this down to see if there is any feedback.
