### DISCUSSION TITLE
ArchDoc Specification - Workflows

### DISCUSSION THREAD

**Discussion by mtfuller** [ArchDoc/ArchDoc.github.io#4] [Ideas]
The ability to be able to walk a user through a system design would be super helpful. Tools like Ice Panel already have this in place. I advocate that the ArchDoc Specification is updated to define tours of the architecture model.

Perhaps, this can look something like this:
```yaml
workflows:
  userPublishesPost:
    description: A user creates a post and publishes it to the blog
    flow:
      - user -> ui: Writes post and hits Publish button
      - ui -> api: Create new Post record
      - api -> db: Persist Post to the database
```
